<?php
/**
 * Description
 *
 * @package     ($namespace)
 * @since       1.0.0
 * @author      brs
 * @link        https://bowriverstudio.com
 * @license     GNU General Public License 2.0+
 */


acf_register_block( array(
	'name'			=> 'LDA Gallery',
	'title'			=> __( 'LDA Gallery', '' ),
	'render_template'	=> LDABLOCKSDIR . 'partials/lda-gallery.php',
	'category'		=> 'formatting',
	'icon'			=> 'images-alt2',
	'keywords'		=> array( 'image', 'project' ),
	'mode'			=> 'edit',
	'supports'		=> array( 'mode' => false )
));

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_60400daecd234',
	'title' => 'LDA Gallery',
	'fields' => array(
		array(
			'key' => 'field_60400db888001',
			'label' => 'Year',
			'name' => 'year',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 2021,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => 4,
		),
		array(
			'key' => 'field_6040136596c04',
			'label' => 'Project Name',
			'name' => 'project_name',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_6040137f96c05',
			'label' => 'Project Description',
			'name' => 'project_description',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_604013a796c06',
			'label' => 'Size',
			'name' => 'size',
			'type' => 'number',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => 'Sq.Ft',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array(
			'key' => 'field_604013db96c07',
			'label' => 'Area',
			'name' => 'area',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_6040145596c08',
			'label' => 'Items',
			'name' => 'items',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_604014ad96c09',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Add Item',
			'sub_fields' => array(
				array(
					'key' => 'field_604014ad96c09',
					'label' => 'Layout',
					'name' => 'layout',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'layout-1' => 'Full width image',
						'layoyt-1-text' => 'Full width text',
						'layout-1-1' => 'Two images (1/1)',
						'layout-2-1' => 'Two images (2/1)',
						'layout-1-2' => 'Two images (1/2)',
						'layout-1-1-1' => 'Three images (1/1/1)',
						'layout-1-1-1-1' => 'Four images (1/1/1/1)',
						'layout-1-2-text-image' => 'Text + Image (1/2)',
						'layout-2-1-text-image' => 'Image + Text (2/1)',
						'layout-1-1-1-text-left' => 'Text + Two images (1/1/1)',
						'layout-1-1-1-text-right' => 'Text + Two images (1/1/1)',
					),
					'default_value' => 'layout-1',
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 1,
					'ajax' => 0,
					'return_format' => 'value',
					'placeholder' => '',
				),
				array(
					'key' => 'field_604018c796c0a',
					'label' => 'Image 1',
					'name' => 'image_1',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_604014ad96c09',
								'operator' => '!=',
								'value' => 'layoyt-1-text',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_6040190396c0c',
					'label' => 'Image 2',
					'name' => 'image_2',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_604014ad96c09',
								'operator' => '!=',
								'value' => 'layout-1',
							),
							array(
								'field' => 'field_604014ad96c09',
								'operator' => '!=',
								'value' => 'layoyt-1-text',
							),
							array(
								'field' => 'field_604014ad96c09',
								'operator' => '!=',
								'value' => 'layout-1-2-text-image',
							),
							array(
								'field' => 'field_604014ad96c09',
								'operator' => '!=',
								'value' => 'layout-2-1-text-image',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_604019a396c10',
					'label' => 'Image 3',
					'name' => 'image_3',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_604014ad96c09',
								'operator' => '==',
								'value' => 'layout-1-1-1',
							),
						),
						array(
							array(
								'field' => 'field_604014ad96c09',
								'operator' => '==',
								'value' => 'layout-1-1-1-1',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_60402258700ef',
					'label' => 'Image 4',
					'name' => 'image_4',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_604014ad96c09',
								'operator' => '==',
								'value' => 'layout-1-1-1-1',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_604019d296c13',
					'label' => 'Text',
					'name' => 'text',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_604014ad96c09',
								'operator' => '==contains',
								'value' => 'text',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => '',
					'new_lines' => '',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'block',
				'operator' => '==',
				'value' => 'acf/lda-gallery',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

endif;
